[project]
name = "movies_scraper"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "s1lver29", email = "None"},
]
dependencies = ["scrapy>=2.12.0"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "None"}


[tool.pdm]
distribution = false
